### ISSUE TITLE
INFOGRAFIA DE LA S¿

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/infografia-de-las-librerias-magaly1311#2]
[INFOGRAFIA DE LIBRERIAS  MAGALY NICOLAS SANCHEZ .pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-magaly1311/files/8219530/INFOGRAFIA.DE.LIBRERIAS.MAGALY.NICOLAS.SANCHEZ.pdf)

**Comment by JudithReynaCS** [comment]
Calificacion :20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
